CREATE TABLE IF NOT EXISTS `form_nursing_note` (
`id`                bigint(20)      NOT NULL auto_increment,
`date`              datetime        default NULL,
`pid`               bigint(20)      default 0,
`user`              varchar(255)    default NULL,
`groupname`         varchar(255)    default NULL,
`authorized`        tinyint(4)      default 0,
`activity`          tinyint(4)      default 0,
`pain`	    		VARCHAR(40)     default NULL,
`acuity_od`	        VARCHAR(10)     default NULL,
`acuity_os`	        VARCHAR(10)     default NULL,
`acuity_ou`	        VARCHAR(10)     default NULL,
`acuity_correction` BOOLEAN,
`ishihara`	        VARCHAR(40)     default NULL,
`injection_mfr`     VARCHAR(40)     default NULL,
`injection_lot`     VARCHAR(40)     default NULL,
`injection_loc`     VARCHAR(40)     default NULL,
`injection_exp`     DATE,
`ecg`	     	    BOOLEAN,
`abi`	       	    BOOLEAN,
`svn`	       	  	BOOLEAN,
`venipuncture`	    BOOLEAN,
`allergy_testing`   BOOLEAN,
`suture_removal`    BOOLEAN,
`wound_care`    	BOOLEAN,
`tb_test`    		VARCHAR(1)      default 0,
`rx_refill`    		BOOLEAN,
`patient_edu`    	BOOLEAN,
`notes`             VARCHAR(255)    default NULL,

PRIMARY KEY (id)
) ENGINE=MyISAM;